FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

ARG AIRFLOW_VERSION=2.10.2
ENV AIRFLOW_HOME=/workspaces/Apache_Airflow_Tutorial/.airflow_home
ENV AIRFLOW__CORE__DAGS_FOLDER=/workspaces/Apache_Airflow_Tutorial/dags

# Install Apache Airflow using official constraints
RUN pip install --no-cache-dir --upgrade pip setuptools wheel \
    && PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")') \
    && CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt" \
    && pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"

# Explicitly set up the explicit directories
RUN mkdir -p ${AIRFLOW_HOME} /workspaces/Apache_Airflow_Tutorial/dags